def display(wrong):
    if wrong == 0:
        print(' ___ ')
        print('|   |')
        print('|  ')
        print('|   ')
        print('|   ')
        print('-------')
        print()
    elif wrong == 1:
        print(' ___ ')
        print('|   |')
        print('|   o')
        print('|   ')
        print('|  ')
        print('-------')
        print()
    elif wrong == 2:
        print(' ___ ')
        print('|   |')
        print('|  \\o')
        print('|   ')
        print('|  ')
        print('-------')
        print()
    elif wrong == 3:
        print(' ___ ')
        print('|   |')
        print('|  \\o/')
        print('|   ')
        print('|   ')
        print('-------')
        print()
    elif wrong == 4:
        print(' ___ ')
        print('|   |')
        print('|  \\o/')
        print('|   |')
        print('|   ')
        print('-------')
        print()
    elif wrong == 5:
        print(' ___ ')
        print('|   |')
        print('|  \\o/')
        print('|   |')
        print('|  /  ')
        print('-------')
        print()
    elif wrong == 6:
        print(' ___ ')
        print('|   |')
        print('|  \\o/')
        print('|   |')
        print('|  / \\ ')
        print('-------')
        print()
    else:
        print('Bad -wrong- input')
